### ISSUE TITLE
Add calendar date

### ISSUE THREAD

**Issue by vdl2103** [vdl2103/nndssdata#1]
Data currently has only CDC week; want to add the actual date associated with the CDC week.

**Comment by jordan27r** [comment]
Package: MMWRweek

Sample code: 
```
library(tidyverse)
library(MMWRweek)

sample <- data.frame(week = c(4, 15, 26, 42), year = c(2008, 2009, 2010, 2015))

sample %>% 
  mutate(StartDate = MMWRweek2Date(year, week))
```

Output:

  week year  StartDate
1    4 2008 2008-01-20
2   15 2009 2009-04-12
3   26 2010 2010-06-27
4   42 2015 2015-10-18
